# Generated by Django 4.0.4 on 2022-05-28 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('static_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField()),
                ('format', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Media attachment',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('is_enabled', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
            },
        ),
        migrations.DeleteModel(
            name='UploadedMedia',
        ),
        migrations.AddField(
            model_name='attachment',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_content.media'),
        ),
    ]
