# Generated by Django 4.0.4 on 2022-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmedia',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=50),
            preserve_default=False,
        ),
    ]
