# Generated by Django 4.0.4 on 2022-05-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0002_attachment_media_delete_uploadedmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='att', max_length=30),
        ),
    ]
