# Generated by Django 4.0.4 on 2022-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0005_alter_attachment_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='uri',
            field=models.CharField(max_length=500),
        ),
    ]
