# Generated by Django 4.0.4 on 2022-06-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0008_alter_media_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='static_content.media', unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
