# Generated by Django 4.0.4 on 2022-06-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0009_alter_attachment_media_alter_media_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='static_content.media'),
        ),
    ]
