# Generated by Django 4.0.4 on 2022-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0019_attachment_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='editor_choice',
            field=models.BooleanField(default=False),
        ),
    ]
