version: '3.8'
services:
  frontend:
    build: ./react-frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://localhost:8000/
    depends_on:
      - api
  api:
    build: ./django_backend
    ports:
      - 8000:8000
    volumes:
      - ./django_backend:/webapp:cached
    env_file:
      - ./django_backend/django_backend/.env
    environment:
      DB_HOST: db
      DB_NAME: gdsd
    depends_on:
      - db
    command: ./scripts/run_backend.sh
    
  websocket:
    build: ./django_backend
    ports:
      - 8001:8001
    volumes:
      - ./django_backend:/webapp:cached
    env_file:
      - ./django_backend/django_backend/.env
    environment:
      DB_HOST: db
      DB_NAME: gdsd
      REDIS_HOST: redis
    depends_on:
      - api
    command: daphne -b 0.0.0.0 -p 8001 django_backend.asgi:application

  db:
    image: mysql:latest
    ports:
     - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gdsd
    # volumes:
    #   - ./mysql_data:/var/lib/mysql
      # - /Users/segullshairbutt/Desktop/Academics/GSD/GSD-Team-3/mysqld:/run/mysqld
  redis:
    image: redis:5
    ports:
      - 6379:6379

volumes:
  mysql_data: